### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [hollowshiroyuki/minitek#1]
Hi. Have you decided on a license for your project?

**Comment by hollowshiroyuki** [comment]
uuh i don't think this mess of a project needs a license, no one in their right mind would want to use this for anything else than crashing their computer

**Comment by LifeCANvs** [comment]
Oh :(
I help some teenagers to learn programming and I like to give them some example code (whether good or "bad") to look at and experiment with... maybe they will find some good "snippets" in there and then be able to build on those in what ever they try to create themselves. I already explained to them about copyright and licenses, so for that to be possible, we need to what license applies to the code used as examples... Unfortunately I could not find other pure C code (non-C++) for this type of simple top-down RPG game. So I'm hoping you would reconsider - especially if you don't care about using the code yourself anymore.

**Comment by hollowshiroyuki** [comment]
added a *permissive* license, this should be okay ?

**Comment by LifeCANvs** [comment]
> added a _permissive_ license, this should be okay ?

Thank you so much!
